//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CrabRemoteServer.rc 使用
//
#define IDR_SERVER_DIALOG_MAIN_TOOL_BAR 4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CRABREMOTESERVER_DIALOG     102
#define IDR_STATUSBAR_SERVER_STRING     102
#define IDR_STATUSBAR_FILE_MANAGER_PROGRESS 103
#define IDR_MAINFRAME                   128
#define CRAB_DIALOG_MAIN_MENU           130
#define IDR_TOOLBAR1                    131
#define IDR_NOTIFY_ICON_DATA_MENU       133
#define IDB_SERVER_DIALOG_MAIN_BITMAP   137
#define IDD_SERVER_MANAGER_DIALOG       139
#define IDB_PNG_SERVER_MANAGER          144
#define IDI_ICO_SEVER_MANAGER           145
#define IDR_CLIENT_INFO_LIST_MENU       146
#define IDD_INSTANT_MESSAGE_DIALOG      147
#define IDD_PROCESS_MANAGER_DIALOG      149
#define IDR_CLIENT_PROCESS_MENU         151
#define IDR_PROCESS_MANAGER_DIALOG_MAIN_MENU 152
#define IDD_CREATE_PROCESS_DIALOG       153
#define IDD_MEMORY_EDITOR_DIALOG        157
#define IDD_CHANGE_VALUE_DIALOG         159
#define IDD_PROCESS_VMMAP_DIALOG        161
#define IDD_CMD_MANAGER_DIALOG          163
#define IDD_WINDOW_MANAGER_DIALOG       165
#define IDR_CLIENT_WINDOW_MENU          167
#define IDD_REMOTE_CONTROL_DIALOG       170
#define IDD_FILE_MANAGER_DIALOG         172
#define IDB_FILE_MANAGER_BITMAP         174
#define IDR_SERVER_FILE_TOOLBAR         175
#define IDR_CLIENT_FILE_TOOLBAR         177
#define IDC_MULTI_CURSOR                180
#define IDC_SINGLE_CURSOR               181
#define IDD_FILE_TRANSFER_MODE_DIALOG   182
#define IDD_FILE_NEW_FOLDER_DIALOG      184
#define CRAB_SERVER_INFORMATION_LIST    1000
#define CRAB_CLIENT_INFORMATION_LIST    1001
#define IDC_SET_LISTEN_PORT             1003
#define IDC_SET_MAX_CONNECTS            1004
#define IDC_APPLY_BUTTON                1005
#define IDC_SERVER_INFORMATION_LIST     1006
#define IDC_PROCESS_INFO_LIST           1007
#define IDC_PROCESS_CREATE_EDIT         1008
#define IDC_PROCESS_CREATE_BUTTON       1009
#define IDC_PROCESS_ID_IN_EDITOR_EDIT   1016
#define IDC_FIRST_SCAN_BUTTON           1017
#define IDC_SECOND_SCAN_BUTTON          1018
#define IDC_UNDO_SCAN_BUTTON            1019
#define IDC_VALUE_CHANGE_EDIT           1020
#define IDC_MEMORY_EDITOR_LIST          1022
#define IDC_CURRENT_ADDRESS_EDIT        1023
#define IDC_NEW_VALUE_EDIT              1024
#define IDC_NEW_VALUE_BUTTON            1025
#define IDC_MEMORY_PAGE_SIZE_EDIT       1026
#define IDC_TOTAL_PHYSICAL_MEMORY_EDIT  1027
#define IDC_ACCESS_PHYSICAL_MEMORY_EDIT 1028
#define IDC_MINIMAL_ADDRESS_EDIT        1029
#define IDC_MAXIMUM_ADDRESS_EDIT        1030
#define IDC_TOTAL_PAGE_FILE_EDIT        1031
#define IDC_ACCESS_PAGE_FILE_EDIT       1032
#define IDC_TOTAL_VIRTUAL_MEMORY_EDIT   1033
#define IDC_ACCESS_VIRTUAL_MEMORY_EDIT  1034
#define IDC_VMMAP_PROCESS_ID_EDIT       1035
#define IDC_VMMAP_PROCESS_PATH_EDIT     1036
#define IDC_VMMAP_MEMORY_LIST_DIALOG    1037
#define IDC_VMMAP_COMMIT_CHECK          1038
#define IDC_VMMAP_RESERVE_CHECK         1039
#define IDC_VMMAP_REFRESH_BUTTON        1040
#define IDC_VMMAP_FREE_CHECK            1041
#define IDC_CMD_MANAGER_EDIT            1041
#define IDC_SCROLLBAR2                  1043
#define IDC_WINDOW_MANAGER_LIST         1044
#define IDC_CLIENT_FILE_LIST            1045
#define IDC_SERVER_FILE_LIST            1046
#define IDC_SERVER_FILE_COMBO           1047
#define IDC_CLIENT_FILE_COMBO           1048
#define IDC_CLIENT_POSITION_STATIC      1049
#define IDC_SERVER_POSITION_STATIC      1050
#define IDC_COVER_BUTTON                1050
#define IDC_ALL_COVER_BUTTON            1051
#define IDC_JMP_BUTTON                  1052
#define IDC_ALL_JMP_BUTTON              1053
#define IDC_CANCEL_BUTTON               1054
#define IDC_TIPS_STATIC                 1055
#define IDC_EDIT1                       1056
#define IDC_NEW_FOLDER_EDIT             1056
#define ID_MENU_EXIT                    32775
#define ID_MENU_SET_LOCAL               32777
#define ID_MENU_ADD_INFORMATION         32780
#define ID_CMD_MANAGER                  32781
#define ID_PROCESS_MANAGER              32782
#define ID_WINDOW_MANAGER               32783
#define ID_REMOTE_CONTROL               32784
#define ID_FILE_MANAGER                 32785
#define ID_AUDIO_MANAGER                32786
#define ID_CLEAN_MANAGER                32787
#define ID_VIDEO_MANAGER                32788
#define ID_SERVICE_MANAGER              32789
#define ID_REGISTER_MANAGER             32790
#define ID_SERVER_MANAGER               32791
#define ID_CLIENT_MANAGER               32792
#define ID_SERVER_ABOUT                 32793
#define ID_SHOW_MAIN_DIALOG             32796
#define ID_HIDE_MAIN_DIALOG             32798
#define ID_DELETE_CONNECTION            32803
#define ID_INSTANT_MESSAGE              32804
#define ID_REMOTE_SHUTDOWN              32805
#define ID_REFRESH_PROCESS              32814
#define ID_KILL_PROCESS                 32815
#define ID_SUSPEND_PROCESS              32816
#define ID_RESUME_PROCESS               32817
#define ID_PROCESS_MODULES              32818
#define ID_PROCESS_THREADS              32819
#define ID_PROCESS_MEMORY               32820
#define ID_PROCESS_HANDLES              32821
#define ID_PROCESS_VMMAP                32827
#define ID_REFRESH_WINDOW               32834
#define IID_CLOSE_WINDOW                32835
#define ID_CLOSE_WINDOW                 32836
#define ID_HIDE_WINDOW                  32837
#define ID_RECOVER_WINDOW               32838
#define ID_MAX_WINDOW                   32839
#define ID_MIN_WINDOW                   32840
#define IDT_SERVER_FILE_PREVIOUS        32841
#define IDT_SERVER_FILE_VIEW            32842
#define IDT_SERVER_FILE_DELETE          32843
#define IDT_SERVER_NEW_FOLDER           32844
#define IDT_SERVER_FILE_FINDER          32845
#define IDT_SERVER_FILE_STOP            32846
#define IDT_CLIENT_FILE_PREVIOUS        32847
#define IDT_CLIENT_FILE_VIEW            32848
#define IDT_CLIENT_FILE_DELETE          32849
#define IDT_CLIENT_NEW_FOLDER           32850
#define IDT_CLIENT_FILE_FINDER          32851
#define IDT_CLIENT_FILE_STOP            32852

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32853
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
